plugins {
    id 'com.android.application'
}

android {
    namespace 'in.gov.assam.assac.mrv'
    compileSdkVersion 34

    defaultConfig {
        applicationId 'in.gov.assam.assac.mrv'
        minSdkVersion 24
        targetSdkVersion 34
        versionCode 2
        versionName '2.0.0'
    }

    signingConfigs {
        release {
            if (file("signingKey.keystore").exists()) {
                storeFile file("signingKey.keystore")
                storePassword "CXhThGG5x58X"
                keyAlias "assac-mrv"
                keyPassword "CXhThGG5x58X"
            }
        }
    }

    buildTypes {
        release {
            if (file("signingKey.keystore").exists()) {
                signingConfig signingConfigs.release
            } else {
                signingConfig signingConfigs.debug
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            if (file("signingKey.keystore").exists()) {
                signingConfig signingConfigs.release
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core:1.12.0'
    implementation 'com.google.android.material:material:1.11.0'
}
